### ISSUE TITLE
Wire Frames are up

### ISSUE THREAD

**Issue by RupiDev** [QSport/QSport#2]
/cc @codepathreview

[Prototype1.vp.zip](https://github.com/QSport/QSport/files/158982/Prototype1.vp.zip)

**Comment by RupiDev** [comment]
We used the software JustInMind to make the wireframes

**Comment by vinnyoodles** [comment]
5f1ad55db37dc7981ec37e35f7e8dadd6e03ca87

**Comment by hatu87** [comment]
You need to provide the flow of your wireframe. It's hard to see how users can open each screen and how can they interact with your app.

**Comment by vinnyoodles** [comment]
Added the flow of the wireframes with 972a85e74187dda055a9ddbf2b93f82c613a45ca /cc @codepathreview

**Comment by hatu87** [comment]
:+1: Nice job on the wireframes! Wireframing is a common practice when building apps as it lets you create a blueprint for the app before writing any code. Having a really good blueprint that you can refer to throughout the rest of the project is a really valuable resource and will make it much easier to split up work across your team.

With the wireframes in hand, you should have a good idea of what your app will look like when you finish the project. Next week we'll jump into the data schema.
